CREATE TABLE IF NOT EXISTS `i7b0_ffc_contributions` (
  `id` int(10) unsigned AUTO_INCREMENT NOT NULL,
  `user_id` int(10) unsigned,
  `username` varchar(120),
  `hash` varchar(120),
  `membership_token` varchar(120),
  `first_name` varchar(120),
  `last_name` varchar(120),
  `email_address` varchar(120),
  `address_line_1` varchar(500),
  `address_line_2` varchar(500),
  `city` varchar(200),
  `postal_code` varchar(50),
  `country` varchar(100),
  `gross_amount` decimal(13,2) NOT NULL,
  `invoice_created` int(10) unsigned NOT NULL DEFAULT 0,
  `payment_received` int(10) unsigned NOT NULL DEFAULT 0,
  `stripe_token` varchar(120) NOT NULL,
  `reference` varchar(120) NOT NULL,
  `status` varchar(120) NOT NULL,
  `error_description` varchar(200),
  `payment_type` varchar(20) NOT NULL,
  `payment_method` varchar(40) NOT NULL,
  `email_sent` tinyint(1) NOT NULL DEFAULT 0,
  `guid` varchar(120) NOT NULL DEFAULT '',
  `signature_data` text,
  `has_provided_signature` tinyint(1) NOT NULL DEFAULT 0,
  `signed_contribution_agreement` blob,
  `contribution_agreement_signature_date` int(10) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;